// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Hushwake_WildkinCore","status":true,"description":"HUSHWAKE Milestone 1A - persistent Wildkin instances and roster.","parameters":{}},
{"name":"Hushwake_BattleSystem","status":true,"description":"HUSHWAKE Milestone 1A - 1v1 Wildkin battle, switching, and lineups.","parameters":{}},
{"name":"Hushwake_BattleLab","status":true,"description":"HUSHWAKE Milestone 1A - direct graybox Battle Lab launcher.","parameters":{}}
];
